# Generated by Django 4.2.10 on 2024-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_category_discussionpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionpost',
            name='category',
            field=models.ManyToManyField(related_name='discussion', to='discussion.category'),
        ),
    ]
