# Generated by Django 4.2.10 on 2024-02-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
