# Generated by Django 4.2.10 on 2024-02-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_discussionpost_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
