# Generated by Django 4.2.10 on 2024-02-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'category'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
